backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: Benjamin-dhoe/breugelhof-decap
media_folder: "src/static/img/uploads"
public_folder: "/static/img/uploads"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Units"
    name: "units"
    folder: "src/units"
    slug: "{{fields.titel | slug}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Titel unit", name: "titel", widget: "string", required: true }
      - { label: "Kleine beschrijving", name: "beschrijving", widget: "string" }
      - { label: "Grootte in mÂ²", name: "grootte", widget: "string", required: true }
      - { label: "Type", name: "type", widget: "select", options: ["Studio", "Appartement"], required: true }
      - { label: "Status", name: "status", widget: "select", options: ["verhuurd", "beschikbaar"], required: true }
      - { label: "Extra tekst in overzicht", name: "disclaimer", widget: "string", required: false }
      - label: "Mezzanine?"
        name: "mezzanine"
        widget: "boolean"
        required: false
      - label: "Eigen sanitair?"
        name: "sanitair"
        widget: "boolean"
        required: false
      - label: "Ingerichte keuken?"
        name: "keuken"
        widget: "boolean"
        required: false
      - label: "Bureau?"
        name: "bureau"
        widget: "boolean"
        required: false
      - label: "Kledingkast?"
        name: "kledingkast"
        widget: "boolean"
        required: false
      - label: "Bed?"
        name: "bed"
        widget: "boolean"
        required: false
      - { label: "Extra content", name: "html", widget: "markdown", required: false }
      - { label: "Hoofdafbeelding", name: "hoofdafbeelding", widget: "image", required: true }
      - label: "Afbeeldingen"
        name: "afbeeldingen"
        widget: "list"
        field:
          label: "Afbeelding"
          name: "image"
          widget: "image"
  - label: "Andere content"
    name: "Andere content"
    files:
      - label: "Gemeenschappelijke info units"
        name: "shared-units"
        file: "src/_includes/partials/bottomsectionunit.html"
        editor:
          preview: false
        fields: 
          - { label: "Titel", name: "titel", widget: "string", required: true }
          - { label: "Tekst", name: "tekst", widget: "string", required: true }
          - { label: "Afbeelding", name: "afbeelding", widget: "image", required: true }
        
